# Data Preparation: Train Data
## Version 1

Three datasets are used:

- [Myanmar ALT](https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/my-alt-190530.zip) from [ALT Treebank Corpus](https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/)
- [Sayar's myPos version 3.0](https://github.com/ye-kyaw-thu/myPOS/blob/master/corpus-ver-3.0/corpus/mypos-ver.3.0.txt)
- https://huggingface.co/datasets/URajinda/myanmar_spoken_corpus_v4_cleaned

These datasets are then preprocessed and normalized into a standardized format for the language model (LM), primarily for KenLM.

## Setup

Use `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` as an access token to get read access on Hugging Face.

In [1]:
!hf auth login

User is already logged in. Use `hf auth login --force` to force re-login.

In [2]:
import pandas as pd
from datasets import load_dataset

## Load All Datasets

In [3]:
!pwd

/home/lawun330/Desktop/burmese-domain-specific-lm/notebooks

In [4]:
df1 = pd.read_csv(
    "../data/train/my-alt-190530-data",
    sep="\t",
    header=None,
    names=["id", "sentence"]
)
df1.head()

            id                                           sentence
0  SNT.80188.1  (ROOT (NOUN (NOUN (NOUN (NOUN (noun (noun ပြင်...
1  SNT.80188.2  (ROOT (NOUN (NOUN (noun (noun အန်ဒရီယာ) (noun ...
2  SNT.80188.3  (ROOT (VERB (NOUN (NOUN (noun (adj ပထမ) (noun ...
3  SNT.80188.4  (ROOT (VERB (NOUN (noun ပေါ်တူဂီ) (adp သည်) ) ...
4  SNT.80188.5  (ROOT (VERB (NOUN (NOUN (noun အီတလီ) (adp သည်)...

In [5]:
with open("../data/train/mypos-ver.3.0.shuf.notag.nopunc.txt", encoding="utf-8") as f:
    lines = f.read().splitlines()
df2 = pd.DataFrame({"text": lines})
df2.head()

                                                text
0  ၁၉၆၂ ခုနှစ် ခန့်မှန်း သန်းခေါင်စာရင်း အရ လူဦးရ...
1  လူ တိုင်း တွင် သင့်မြတ် လျော်ကန် စွာ ကန့်သတ် ထ...
2              ဤ နည်း ကို စစ်ယူ သော နည်း ဟု ခေါ် သည်
3  စာပြန်ပွဲ ဆို တာ က အာဂုံဆောင် အလွတ်ကျက် ထား တဲ...
4                    ဒီ မှာ ကျွန်တော့် သက်သေခံကတ် ပါ

In [6]:
df3 = load_dataset("URajinda/myanmar_spoken_corpus_v4_cleaned")

Repo card metadata block was not found. Setting CardData to empty.

Resolving data files:   0%|          | 0/36 [00:00<?, ?it/s]

In [7]:
list(df3["train"].take(5))

[{'text': 'ကျွန်တော် နည်းနည်း အရွယ်ရလာတော့ ရတဲ့ အချိန်လေးတွေမှာ မေမေဟာ အိမ်နားက မြစ်ထဲကို သွားပြီး ငါးမျှားလေ့ ရှိပါတယ်။'},
 {'text': 'ကျွန်တော် အဲဒီ ငါးဆွပ်ပြုတ်ကို မိန်ရည်ရှက်ရည်သောက်ရင်း အသားတွေကို စားနေတုန်း မေမေက ဘေးကနေ ထိုင်ပြီး ကျွန်တော် စားလို့ ကျန်တဲ့ ပန်းကန်ထဲက အရိုးမှာ ကပ်နေတဲ့ အသားစလေးတွေကို စားနေပါတယ်။'},
 {'text': 'ချမ်းအေးလွန်းတဲ့ ဆောင်းည တစ်ညမှာ ကျွန်တော် တစ်ရေးနိုးလာတော့ မေမေဟာ ဖယောင်းတိုင် မီးကလေးနဲ့ မီးခြစ်ဆံတွေ ဖြည့်နေတုန်းဘဲ ရှိသေးတယ်။'},
 {'text': 'မေမေက ကျွန်တော့်ကို ဆီးဖက်လိုက်ပြီး ဓာတ်ဗူးထဲမှာ ထည့်လာတဲ့ လ္ဘက်ရည်ကို ခွက်ထဲ ငှဲ့ပြီး ကျွန်တော်သောက်ဖို့ ပေးတယ်။'},
 {'text': 'နေပူထဲ ရပ်နေလို့ ချွေးတွေထွက်နေတဲ့ မေမေ့ကို ကြည့်ပြီး ကျွန်တော်ရဲ့ လ္ဘက်ရည်ခွက်ကို မေမေ့ကို ကမ်းပေးလိုက်ပြီး အတူတူ သောက်ဖို့ ပြောတော့ မေမေက သားဘဲ သောက်စမ်းပါ သားရယ်။'}]

In [8]:
df3

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 7739601
    })
})

### Remove Uncessary Data

- The first dataset contains an unnecessary column: `id`.
- The third dataset is in dictionary format, so it has to be converted into a dataframe.

In [9]:
df1_new = df1.drop(columns=["id"])
df1_new = df1_new.rename(columns={"sentence": "text"})  # optional
df1_new.head()

                                                text
0  (ROOT (NOUN (NOUN (NOUN (NOUN (noun (noun ပြင်...
1  (ROOT (NOUN (NOUN (noun (noun အန်ဒရီယာ) (noun ...
2  (ROOT (VERB (NOUN (NOUN (noun (adj ပထမ) (noun ...
3  (ROOT (VERB (NOUN (noun ပေါ်တူဂီ) (adp သည်) ) ...
4  (ROOT (VERB (NOUN (NOUN (noun အီတလီ) (adp သည်)...

In [10]:
df3_new = df3["train"].to_pandas()
df3_new.head()

                                                text
0  ကျွန်တော် နည်းနည်း အရွယ်ရလာတော့ ရတဲ့ အချိန်လေး...
1  ကျွန်တော် အဲဒီ ငါးဆွပ်ပြုတ်ကို မိန်ရည်ရှက်ရည်သ...
2  ချမ်းအေးလွန်းတဲ့ ဆောင်းည တစ်ညမှာ ကျွန်တော် တစ်...
3  မေမေက ကျွန်တော့်ကို ဆီးဖက်လိုက်ပြီး ဓာတ်ဗူးထဲမ...
4  နေပူထဲ ရပ်နေလို့ ချွေးတွေထွက်နေတဲ့ မေမေ့ကို ကြ...

## Merge All Datasets

In [11]:
print(df1_new.shape)
print(df2.shape)
print(df3_new.shape)

(20106, 1)
(43196, 1)
(7739601, 1)

In [12]:
df = pd.concat([df1_new, df2, df3_new], ignore_index=True)
df.head()

                                                text
0  (ROOT (NOUN (NOUN (NOUN (NOUN (noun (noun ပြင်...
1  (ROOT (NOUN (NOUN (noun (noun အန်ဒရီယာ) (noun ...
2  (ROOT (VERB (NOUN (NOUN (noun (adj ပထမ) (noun ...
3  (ROOT (VERB (NOUN (noun ပေါ်တူဂီ) (adp သည်) ) ...
4  (ROOT (VERB (NOUN (NOUN (noun အီတလီ) (adp သည်)...

In [13]:
print(df.shape)

(7802903, 1)

In [14]:
df["text"].to_csv("../data/train/combined_raw.txt", index=False, header=False, lineterminator="\n")

## Preprocess All Datasets

### Remove Punctuations and Word Tags

The goal of this project is to use KenLM. Therefore, all annotations are removed for now to create a standard corpus.

In [15]:
!python ../clean_text.py -i ../data/train/combined_raw.txt -o ../data/train/combined_cleaned.txt

Success! Cleaned text saved to: ../data/train/combined_cleaned.txt

## Load Final Dataset

new_df = pd.read_csv("../data/train/combined_cleaned.txt", header=None, names=["text"])
new_df

The above code cannot be run because the combined data cannot be loaded into a pandas DataFrame due to RAM limitations. The file is too large (above 3 GB), as indicated by the code below.

## Exploring the Final Dataset File Size

In [16]:
!ls -lh ../data/train/combined_raw.txt ../data/train/combined_cleaned.txt

-rw-rw-r-- 1 lawun330 lawun330 3.2G May 14 18:27 ../data/train/combined_cleaned.txt
-rw-rw-r-- 1 lawun330 lawun330 3.4G May 14 18:23 ../data/train/combined_raw.txt